---
# setup vagrant machine for development

- hosts: all
  remote_user: vagrant
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: add nodesource key to apt
      apt_key:
        url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
        state: present

    - name: make sure node ppa is available
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_4.x trusty main'
        state: present

    - name: update apt-cache if needed
      apt: update_cache=yes

    - name: install apt packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - git
        - nodejs

    - name: make sure nodejs is installed
      apt: name=nodejs state=present

    - name: install npm packages
      npm:
        name: "{{item}}"
        global: yes
      with_items:
        - npm
        - n
        - test262-harness

    - name: use latest node version using n
      command: n latest

    - name: test262 files
      git:
        repo: https://github.com/tc39/test262.git
        dest: /srv/test262/

    - name: run tests
      command: test262-harness test/built-ins
      args:
        chdir: /srv/test262/

    # - name: make sure nginx is installed
    #   apt: name=nginx state=present

    # - name: make sure postgresql is installed
    #   apt: name=postgresql state=present
    #   environment:
    #     LC_ALL: en_US.UTF-8

    # - name: make sure postgresql contrib extensions are installed
    #   apt: name=postgresql-contrib state=present
