---
# setup vagrant machine for development

- hosts: all
  remote_user: vagrant
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: make sure node ppa is available
      apt_repository: repo='ppa:chris-lea/node.js'

    - name: update apt-cache if needed
      apt: update_cache=yes

    - name: make sure git is installed
      apt: name=git state=present

    - name: make sure nodejs is installed
      apt: name=nodejs state=present

    # use npm module when this issue is resolved:
    # https://github.com/ansible/ansible-modules-extras/issues/137
    - name: make sure the latest npm is installed
      command: npm install -g npm

    # https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up
    - name: install Google's depot tools to fetch and sync v8
      git:
        repo=https://chromium.googlesource.com/chromium/tools/depot_tools.git
        dest=/srv/depot_tools

    - name: fetch v8
      git:
        repo=https://chromium.googlesource.com/v8/v8.git
        dest=/srv/v8

    - name: config gclient
      command: /srv/depot_tools/gclient config "https://chromium.googlesource.com/v8/v8.git"
      args:
        chdir: /srv/v8/
        creates: /srv/.gclient

    # https://github.com/v8/v8/wiki/Building%20with%20Gyp#building-v8
    - name: sync v8 folder
      command: /srv/depot_tools/gclient sync
      args:
        chdir: /srv/v8/

    - name: build v8 (Grab a coffee)
      make:
        chdir: /srv/v8/
        target: native

    - name: install test262-harness globally
      npm:
        name: test262-harness
        global: yes

    - name: test262 files
      git:
        repo: https://github.com/tc39/test262.git
        dest: /srv/test262/

    - name: run tests
      command: test262-harness test/built-ins
      args:
        chdir: /srv/test262/

    # - name: make sure nginx is installed
    #   apt: name=nginx state=present

    # - name: make sure postgresql is installed
    #   apt: name=postgresql state=present
    #   environment:
    #     LC_ALL: en_US.UTF-8

    # - name: make sure postgresql contrib extensions are installed
    #   apt: name=postgresql-contrib state=present
